#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : Atelier2_bd.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Thu Feb 10 11:51:36 -0500 2022
# SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: Atelier2_bd.sh [-help]
# usage: Atelier2_bd.sh [-lib_map_path]
# usage: Atelier2_bd.sh [-noclean_files]
# usage: Atelier2_bd.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'Atelier2_bd.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip axi_infrastructure_v1_1_0 axi_vip_v1_1_8 processing_system7_vip_v1_0_10 xil_defaultlib lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 axi_lite_ipif_v3_0_4 v_tc_v6_2_1 v_tc_v6_1_13 v_vid_in_axi4s_v4_0_9 v_axi4s_vid_out_v4_0_11 xlconstant_v1_1_7 smartconnect_v1_0 axi_register_slice_v2_1_22 v_vscaler_v1_1_0 v_hscaler_v1_1_0 axis_infrastructure_v1_1_0 axis_register_slice_v1_1_22 axis_subset_converter_v1_1_22 interrupt_control_v3_1_4 axi_gpio_v2_0_24 axis_data_fifo_v2_0_4 xlslice_v1_0_2)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "Atelier2_bd.sh - Script generated by export_simulation (Vivado v2020.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_8 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/94c3/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_10 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_processing_system7_0_0/sim/Atelier2_bd_processing_system7_0_0.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_clk_wiz_0_0/Atelier2_bd_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_clk_wiz_0_0/Atelier2_bd_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_proc_sys_reset_0_0/sim/Atelier2_bd_proc_sys_reset_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work v_tc_v6_2_1 $vhdlan_opts \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/cd2e/hdl/v_tc_v6_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_tc_0_0/sim/Atelier2_bd_v_tc_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work v_tc_v6_1_13 $vhdlan_opts \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/b92e/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_vid_in_axi4s_v4_0_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/b2aa/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_axi4s_vid_out_v4_0_11 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/1a1e/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_axi4s_vid_out_0_0/sim/Atelier2_bd_v_axi4s_vid_out_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d57c/src/ClockGen.vhd" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d57c/src/SyncAsync.vhd" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d57c/src/SyncAsyncReset.vhd" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d57c/src/DVI_Constants.vhd" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d57c/src/OutputSERDES.vhd" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d57c/src/TMDS_Encoder.vhd" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d57c/src/rgb2dvi.vhd" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_rgb2dvi_0_0/sim/Atelier2_bd_rgb2dvi_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/sim/bd_47db.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_0/sim/bd_47db_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_1/sim/bd_47db_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_2/sim/bd_47db_arinsw_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_3/sim/bd_47db_rinsw_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_4/sim/bd_47db_awinsw_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_5/sim/bd_47db_winsw_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_6/sim/bd_47db_binsw_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_7/sim/bd_47db_aroutsw_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_8/sim/bd_47db_routsw_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_9/sim/bd_47db_awoutsw_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_10/sim/bd_47db_woutsw_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_11/sim/bd_47db_boutsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_12/sim/bd_47db_arni_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_13/sim/bd_47db_rni_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_14/sim/bd_47db_awni_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_15/sim/bd_47db_wni_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_16/sim/bd_47db_bni_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ea34/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_17/sim/bd_47db_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/4fd2/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_18/sim/bd_47db_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8047/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_19/sim/bd_47db_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/b89e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_20/sim/bd_47db_s00a2s_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_21/sim/bd_47db_sarn_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_22/sim/bd_47db_srn_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_23/sim/bd_47db_sawn_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_24/sim/bd_47db_swn_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_25/sim/bd_47db_sbn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/7005/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_26/sim/bd_47db_m00s2a_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_27/sim/bd_47db_m00arn_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_28/sim/bd_47db_m00rn_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_29/sim/bd_47db_m00awn_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_30/sim/bd_47db_m00wn_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_31/sim/bd_47db_m00bn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/7bd7/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_32/sim/bd_47db_m00e_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_33/sim/bd_47db_m01s2a_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_34/sim/bd_47db_m01arn_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_35/sim/bd_47db_m01rn_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_36/sim/bd_47db_m01awn_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_37/sim/bd_47db_m01wn_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_38/sim/bd_47db_m01bn_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_39/sim/bd_47db_m01e_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_40/sim/bd_47db_m02s2a_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_41/sim/bd_47db_m02arn_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_42/sim/bd_47db_m02rn_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_43/sim/bd_47db_m02awn_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_44/sim/bd_47db_m02wn_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_45/sim/bd_47db_m02bn_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_46/sim/bd_47db_m02e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/af2c/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_0/sim/bd_c800_smartconnect_0_0.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_c800_vsc_0_AXIvideo2MultiPixStream.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_c800_vsc_0_Block_split4_proc.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_c800_vsc_0_CTRL_s_axi.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_c800_vsc_0_fifo_w8_d2_S.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_c800_vsc_0_fifo_w8_d3_S.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_c800_vsc_0_fifo_w10_d2_S.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_c800_vsc_0_fifo_w10_d4_S.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_c800_vsc_0_fifo_w11_d2_S.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_c800_vsc_0_fifo_w24_d16_S.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_c800_vsc_0_fifo_w32_d4_S.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_c800_vsc_0_hls_deadlock_detection_unit.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_c800_vsc_0_mac_muladd_8ns_16s_13ns_24_4_1.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_c800_vsc_0_mac_muladd_8ns_16s_24s_25_4_1.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_c800_vsc_0_mac_muladd_8ns_16s_25s_26_4_1.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_c800_vsc_0_mac_muladd_8ns_16s_26s_26_4_1.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_c800_vsc_0_mac_muladd_8ns_16s_26s_27_4_1.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_c800_vsc_0_mac_muladd_8ns_16s_27s_27_4_1.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_c800_vsc_0_MultiPixStream2AXIvideo.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_c800_vsc_0_reg_unsigned_short_s.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_c800_vsc_0_regslice_both.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_c800_vsc_0_start_for_AXIvideo2MultiPixStream_U0.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_c800_vsc_0_start_for_MultiPixStream2AXIvideo_U0.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_c800_vsc_0_start_for_v_vcresampler_core_U0.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_c800_vsc_0_v_vcresampler_core.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_c800_vsc_0_v_vcresampler_core_linebuf_c_val_V_2.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_c800_vsc_0_v_vcresampler_core_linebuf_y_val_V_0.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_c800_vsc_0_v_vcresampler_core_linebuf_y_val_V_1.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_c800_vsc_0_vscale_core_polyphase.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_c800_vsc_0_vscale_core_polyphase_FiltCoeff_0.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_c800_vsc_0_vscale_core_polyphase_LineBuf_val_V_0.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_c800_vsc_0_v_vscaler.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_vscaler_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/v_vscaler_v1_1_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/sim/bd_c800_vsc_0.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_AXIvideo2MultiPixStream.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_Block_split1_proc.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_Block_split12_proc.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_CTRL_s_axi.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_fifo_w1_d2_S.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_fifo_w1_d6_S.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_fifo_w1_d7_S.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_fifo_w8_d2_S.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_fifo_w24_d16_S.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_hls_deadlock_detection_unit.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_hscale_core_polyphase.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_hscale_core_polyphase_FiltCoeff_0_0.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_hscale_polyphase.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_mac_muladd_8ns_16s_13ns_24_4_1.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_mac_muladd_8ns_16s_24s_25_4_1.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_mac_muladd_8ns_16s_25s_26_4_1.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_mac_muladd_8ns_16s_26s_26_4_1.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_mac_muladd_8ns_16s_26s_27_4_1.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_mac_muladd_8ns_16s_27s_27_4_1.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_MultiPixStream2AXIvideo.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_MultiPixStream2AXIvideo_mapComp.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_mux_32_8_1_1.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_mux_83_8_1_1.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_reg_ap_uint_9_s.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_regslice_both.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_start_for_AXIvideo2MultiPixStream_U0.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_start_for_Block_split1_proc_U0.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_start_for_MultiPixStream2AXIvideo_U0.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_start_for_v_hcresampler_core_U0.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_start_for_v_hscaler_entry32_U0.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_start_for_v_vcresampler_core_U0.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_v_hcresampler_core.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_v_hcresampler_core26.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_v_hscaler_entry4.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_v_hscaler_entry32.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_v_vcresampler_core.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_v_vcresampler_core_linebuf_c_val_V_0.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_v_vcresampler_core_linebuf_y_val_V_0.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_c800_hsc_0_v_hscaler.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_hscaler_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/v_hscaler_v1_1_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/sim/bd_c800_hsc_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_register_slice_v1_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ebcc/hdl/axis_register_slice_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_3/hdl/tdata_bd_c800_input_size_set_0.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_3/hdl/tuser_bd_c800_input_size_set_0.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_3/hdl/tstrb_bd_c800_input_size_set_0.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_3/hdl/tkeep_bd_c800_input_size_set_0.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_3/hdl/tid_bd_c800_input_size_set_0.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_3/hdl/tdest_bd_c800_input_size_set_0.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_3/hdl/tlast_bd_c800_input_size_set_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_subset_converter_v1_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/69d9/hdl/axis_subset_converter_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_3/hdl/top_bd_c800_input_size_set_0.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_3/sim/bd_c800_input_size_set_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_4/sim/bd_c800_rst_axis_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_24 $vhdlan_opts \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/4318/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_5/sim/bd_c800_reset_sel_axis_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_6/sim/bd_c800_axis_register_slice_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_data_fifo_v2_0_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/abd4/hdl/axis_data_fifo_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_7/sim/bd_c800_axis_fifo_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlslice_v1_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/11d0/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_8/sim/bd_c800_xlslice_0_0.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_9/sim/bd_c800_xlslice_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/sim/bd_c800.vhd" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/sim/Atelier2_bd_v_proc_ss_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/sim/bd_10d0.v" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_0/sim/bd_10d0_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_1/sim/bd_10d0_psr0_0.vhd" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_2/sim/bd_10d0_psr_aclk_0.vhd" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_3/sim/bd_10d0_psr_aclk1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_4/sim/bd_10d0_arinsw_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_5/sim/bd_10d0_rinsw_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_6/sim/bd_10d0_awinsw_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_7/sim/bd_10d0_winsw_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_8/sim/bd_10d0_binsw_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_9/sim/bd_10d0_aroutsw_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_10/sim/bd_10d0_routsw_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_11/sim/bd_10d0_awoutsw_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_12/sim/bd_10d0_woutsw_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_13/sim/bd_10d0_boutsw_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_14/sim/bd_10d0_arni_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_15/sim/bd_10d0_rni_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_16/sim/bd_10d0_awni_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_17/sim/bd_10d0_wni_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_18/sim/bd_10d0_bni_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_19/sim/bd_10d0_s00mmu_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_20/sim/bd_10d0_s00tr_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_21/sim/bd_10d0_s00sic_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_22/sim/bd_10d0_s00a2s_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_23/sim/bd_10d0_sarn_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_24/sim/bd_10d0_srn_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_25/sim/bd_10d0_sawn_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_26/sim/bd_10d0_swn_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_27/sim/bd_10d0_sbn_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_28/sim/bd_10d0_m00s2a_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_29/sim/bd_10d0_m00arn_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_30/sim/bd_10d0_m00rn_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_31/sim/bd_10d0_m00awn_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_32/sim/bd_10d0_m00wn_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_33/sim/bd_10d0_m00bn_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_34/sim/bd_10d0_m00e_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_35/sim/bd_10d0_m01s2a_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_36/sim/bd_10d0_m01arn_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_37/sim/bd_10d0_m01rn_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_38/sim/bd_10d0_m01awn_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_39/sim/bd_10d0_m01wn_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_40/sim/bd_10d0_m01bn_0.sv" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_41/sim/bd_10d0_m01e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Programs/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/sim/Atelier2_bd_smartconnect_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_testPatternGenerator_0_0/sim/Atelier2_bd_testPatternGenerator_0_0.vhd" \
    "$ref_dir/../../../bd/Atelier2_bd/sim/Atelier2_bd.vhd" \
    "$ref_dir/../../../bd/Atelier2_bd/ipshared/7950/hdl/myColorRegister_v1_0_S00_AXI.vhd" \
    "$ref_dir/../../../bd/Atelier2_bd/ipshared/7950/hdl/myColorRegister_v1_0.vhd" \
    "$ref_dir/../../../bd/Atelier2_bd/ip/Atelier2_bd_myColorRegister_0_1/sim/Atelier2_bd_myColorRegister_0_1.vhd" \
  2>&1 | tee -a vhdlan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.Atelier2_bd xil_defaultlib.glbl -o Atelier2_bd_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./Atelier2_bd_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./Atelier2_bd.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key Atelier2_bd_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc Atelier2_bd_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./Atelier2_bd.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: Atelier2_bd.sh [-help]\n\
Usage: Atelier2_bd.sh [-lib_map_path]\n\
Usage: Atelier2_bd.sh [-reset_run]\n\
Usage: Atelier2_bd.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
