# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.runs/synth_1/Atelier2_bd_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.cache/wt [current_project]
set_property parent.project_path C:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo-z7-10:part0:1.0 [current_project]
set_property ip_repo_paths {
  c:/Users/freed/Desktop/Atelier2/ip_repo/myColorRegister_1.0
  c:/Users/freed/Desktop/Atelier2/ip_repo/myColorRegister_1.0
  c:/Users/freed/Desktop/FichiersAtelier2/rgb2dvi
  c:/Users/freed/Desktop/FichiersAtelier2/tmds_v1_0
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib {
  C:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.srcs/sources_1/imports/FichiersAtelier2/testPatternGenerator.vhd
  c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/hdl/Atelier2_bd_wrapper.vhd
}
add_files C:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.srcs/sources_1/bd/Atelier2_bd/Atelier2_bd.bd
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_processing_system7_0_0/Atelier2_bd_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_clk_wiz_0_0/Atelier2_bd_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_clk_wiz_0_0/Atelier2_bd_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_clk_wiz_0_0/Atelier2_bd_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_proc_sys_reset_0_0/Atelier2_bd_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_proc_sys_reset_0_0/Atelier2_bd_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_tc_0_0/Atelier2_bd_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_axi4s_vid_out_0_0/Atelier2_bd_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_rgb2dvi_0_0/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_1/bd_47db_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_1/bd_47db_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_2/bd_47db_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_3/bd_47db_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_4/bd_47db_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_5/bd_47db_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_6/bd_47db_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_7/bd_47db_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_8/bd_47db_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_9/bd_47db_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_10/bd_47db_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_11/bd_47db_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_12/bd_47db_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_13/bd_47db_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_14/bd_47db_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_15/bd_47db_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_16/bd_47db_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_20/bd_47db_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_21/bd_47db_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_22/bd_47db_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_23/bd_47db_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_24/bd_47db_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_25/bd_47db_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_26/bd_47db_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_27/bd_47db_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_28/bd_47db_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_29/bd_47db_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_30/bd_47db_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_31/bd_47db_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_33/bd_47db_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_34/bd_47db_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_35/bd_47db_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_36/bd_47db_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_37/bd_47db_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_38/bd_47db_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_40/bd_47db_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_41/bd_47db_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_42/bd_47db_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_43/bd_47db_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_44/bd_47db_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_45/bd_47db_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/bd_c800_vsc_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/bd_c800_hsc_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_3/bd_c800_input_size_set_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_4/bd_c800_rst_axis_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_4/bd_c800_rst_axis_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_5/bd_c800_reset_sel_axis_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_5/bd_c800_reset_sel_axis_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_5/bd_c800_reset_sel_axis_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_6/bd_c800_axis_register_slice_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/bd_c800_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_1/bd_10d0_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_1/bd_10d0_psr0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_2/bd_10d0_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_2/bd_10d0_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_3/bd_10d0_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_3/bd_10d0_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_4/bd_10d0_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_5/bd_10d0_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_6/bd_10d0_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_7/bd_10d0_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_8/bd_10d0_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_9/bd_10d0_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_10/bd_10d0_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_11/bd_10d0_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_12/bd_10d0_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_13/bd_10d0_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_14/bd_10d0_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_15/bd_10d0_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_16/bd_10d0_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_17/bd_10d0_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_18/bd_10d0_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_22/bd_10d0_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_23/bd_10d0_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_24/bd_10d0_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_25/bd_10d0_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_26/bd_10d0_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_27/bd_10d0_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_28/bd_10d0_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_29/bd_10d0_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_30/bd_10d0_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_31/bd_10d0_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_32/bd_10d0_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_33/bd_10d0_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_35/bd_10d0_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_36/bd_10d0_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_37/bd_10d0_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_38/bd_10d0_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_39/bd_10d0_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_40/bd_10d0_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/Atelier2_bd_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.srcs/constrs_1/imports/FichiersAtelier2/atelier2.xdc
set_property used_in_implementation false [get_files C:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.srcs/constrs_1/imports/FichiersAtelier2/atelier2.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
OPTRACE "compile_c" START { }
compile_c [get_files C:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.srcs/sources_1/bd/Atelier2_bd/Atelier2_bd.bd
]
OPTRACE "compile_c" END { }
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Atelier2_bd_wrapper -part xc7z010clg400-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Atelier2_bd_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Atelier2_bd_wrapper_utilization_synth.rpt -pb Atelier2_bd_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
