# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/FichiersAtelier2/atelier2.xdc

# Block Designs: bd/Atelier2_bd/Atelier2_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Atelier2_bd || ORIG_REF_NAME==Atelier2_bd} -quiet] -quiet

# IP: bd/Atelier2_bd/ip/Atelier2_bd_processing_system7_0_0/Atelier2_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Atelier2_bd_processing_system7_0_0 || ORIG_REF_NAME==Atelier2_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/Atelier2_bd/ip/Atelier2_bd_clk_wiz_0_0/Atelier2_bd_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Atelier2_bd_clk_wiz_0_0 || ORIG_REF_NAME==Atelier2_bd_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Atelier2_bd/ip/Atelier2_bd_proc_sys_reset_0_0/Atelier2_bd_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Atelier2_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==Atelier2_bd_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/Atelier2_bd/ip/Atelier2_bd_v_tc_0_0/Atelier2_bd_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Atelier2_bd_v_tc_0_0 || ORIG_REF_NAME==Atelier2_bd_v_tc_0_0} -quiet] -quiet

# IP: bd/Atelier2_bd/ip/Atelier2_bd_v_axi4s_vid_out_0_0/Atelier2_bd_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Atelier2_bd_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==Atelier2_bd_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/Atelier2_bd/ip/Atelier2_bd_rgb2dvi_0_0/Atelier2_bd_rgb2dvi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Atelier2_bd_rgb2dvi_0_0 || ORIG_REF_NAME==Atelier2_bd_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/Atelier2_bd_v_proc_ss_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Atelier2_bd_v_proc_ss_0_0 || ORIG_REF_NAME==Atelier2_bd_v_proc_ss_0_0} -quiet] -quiet

# Block Designs: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/bd_c800.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c800 || ORIG_REF_NAME==bd_c800} -quiet] -quiet

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_0/bd_c800_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c800_smartconnect_0_0 || ORIG_REF_NAME==bd_c800_smartconnect_0_0} -quiet] -quiet

# Block Designs: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/bd_47db.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_0/bd_47db_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_1/bd_47db_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_2/bd_47db_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_3/bd_47db_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_4/bd_47db_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_5/bd_47db_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_6/bd_47db_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_7/bd_47db_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_8/bd_47db_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_9/bd_47db_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_10/bd_47db_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_11/bd_47db_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_12/bd_47db_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_13/bd_47db_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_14/bd_47db_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_15/bd_47db_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_16/bd_47db_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_17/bd_47db_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_18/bd_47db_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_19/bd_47db_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_20/bd_47db_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_21/bd_47db_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_22/bd_47db_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_23/bd_47db_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_24/bd_47db_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_25/bd_47db_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_26/bd_47db_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_27/bd_47db_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_28/bd_47db_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_29/bd_47db_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_30/bd_47db_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_31/bd_47db_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_32/bd_47db_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_33/bd_47db_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_34/bd_47db_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_35/bd_47db_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_36/bd_47db_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_37/bd_47db_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_38/bd_47db_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_39/bd_47db_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_40/bd_47db_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_41/bd_47db_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_42/bd_47db_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_43/bd_47db_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_44/bd_47db_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_45/bd_47db_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_46/bd_47db_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/bd_c800_vsc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c800_vsc_0 || ORIG_REF_NAME==bd_c800_vsc_0} -quiet] -quiet

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/bd_c800_hsc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c800_hsc_0 || ORIG_REF_NAME==bd_c800_hsc_0} -quiet] -quiet

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_3/bd_c800_input_size_set_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c800_input_size_set_0 || ORIG_REF_NAME==bd_c800_input_size_set_0} -quiet] -quiet

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_4/bd_c800_rst_axis_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c800_rst_axis_0 || ORIG_REF_NAME==bd_c800_rst_axis_0} -quiet] -quiet

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_5/bd_c800_reset_sel_axis_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c800_reset_sel_axis_0 || ORIG_REF_NAME==bd_c800_reset_sel_axis_0} -quiet] -quiet

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_6/bd_c800_axis_register_slice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c800_axis_register_slice_0_0 || ORIG_REF_NAME==bd_c800_axis_register_slice_0_0} -quiet] -quiet

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_7/bd_c800_axis_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c800_axis_fifo_0 || ORIG_REF_NAME==bd_c800_axis_fifo_0} -quiet] -quiet

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_8/bd_c800_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c800_xlslice_0_0 || ORIG_REF_NAME==bd_c800_xlslice_0_0} -quiet] -quiet

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_9/bd_c800_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c800_xlslice_1_0 || ORIG_REF_NAME==bd_c800_xlslice_1_0} -quiet] -quiet

# IP: bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/Atelier2_bd_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Atelier2_bd_smartconnect_0_0 || ORIG_REF_NAME==Atelier2_bd_smartconnect_0_0} -quiet] -quiet

# Block Designs: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/bd_10d0.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_0/bd_10d0_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_1/bd_10d0_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_2/bd_10d0_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_3/bd_10d0_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_4/bd_10d0_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_5/bd_10d0_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_6/bd_10d0_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_7/bd_10d0_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_8/bd_10d0_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_9/bd_10d0_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_10/bd_10d0_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_11/bd_10d0_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_12/bd_10d0_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_13/bd_10d0_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_14/bd_10d0_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_15/bd_10d0_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_16/bd_10d0_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_17/bd_10d0_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_18/bd_10d0_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_19/bd_10d0_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_20/bd_10d0_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_21/bd_10d0_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_22/bd_10d0_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_23/bd_10d0_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_24/bd_10d0_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_25/bd_10d0_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_26/bd_10d0_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_27/bd_10d0_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_28/bd_10d0_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_29/bd_10d0_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_30/bd_10d0_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_31/bd_10d0_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_32/bd_10d0_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_33/bd_10d0_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_34/bd_10d0_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_35/bd_10d0_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_36/bd_10d0_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_37/bd_10d0_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_38/bd_10d0_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_39/bd_10d0_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_40/bd_10d0_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_41/bd_10d0_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/Atelier2_bd/ip/Atelier2_bd_testPatternGenerator_0_0/Atelier2_bd_testPatternGenerator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Atelier2_bd_testPatternGenerator_0_0 || ORIG_REF_NAME==Atelier2_bd_testPatternGenerator_0_0} -quiet] -quiet

# IP: bd/Atelier2_bd/ip/Atelier2_bd_myColorRegister_0_1/Atelier2_bd_myColorRegister_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Atelier2_bd_myColorRegister_0_1 || ORIG_REF_NAME==Atelier2_bd_myColorRegister_0_1} -quiet] -quiet

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_processing_system7_0_0/Atelier2_bd_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Atelier2_bd_processing_system7_0_0 || ORIG_REF_NAME==Atelier2_bd_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_clk_wiz_0_0/Atelier2_bd_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Atelier2_bd_clk_wiz_0_0 || ORIG_REF_NAME==Atelier2_bd_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_clk_wiz_0_0/Atelier2_bd_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Atelier2_bd_clk_wiz_0_0 || ORIG_REF_NAME==Atelier2_bd_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_clk_wiz_0_0/Atelier2_bd_clk_wiz_0_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_proc_sys_reset_0_0/Atelier2_bd_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Atelier2_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==Atelier2_bd_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_proc_sys_reset_0_0/Atelier2_bd_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Atelier2_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==Atelier2_bd_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_tc_0_0/Atelier2_bd_v_tc_0_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Atelier2_bd_v_tc_0_0 || ORIG_REF_NAME==Atelier2_bd_v_tc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_axi4s_vid_out_0_0/Atelier2_bd_v_axi4s_vid_out_0_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Atelier2_bd_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==Atelier2_bd_v_axi4s_vid_out_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_rgb2dvi_0_0/src/rgb2dvi.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Atelier2_bd_rgb2dvi_0_0 || ORIG_REF_NAME==Atelier2_bd_rgb2dvi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Atelier2_bd_rgb2dvi_0_0 || ORIG_REF_NAME==Atelier2_bd_rgb2dvi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_1/bd_47db_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_1/bd_47db_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_2/bd_47db_arinsw_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_3/bd_47db_rinsw_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_4/bd_47db_awinsw_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_5/bd_47db_winsw_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_6/bd_47db_binsw_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_7/bd_47db_aroutsw_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_8/bd_47db_routsw_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_9/bd_47db_awoutsw_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_10/bd_47db_woutsw_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_11/bd_47db_boutsw_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_12/bd_47db_arni_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_13/bd_47db_rni_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_14/bd_47db_awni_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_15/bd_47db_wni_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_16/bd_47db_bni_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_20/bd_47db_s00a2s_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_21/bd_47db_sarn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_22/bd_47db_srn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_23/bd_47db_sawn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_24/bd_47db_swn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_25/bd_47db_sbn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_26/bd_47db_m00s2a_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_27/bd_47db_m00arn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_28/bd_47db_m00rn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_29/bd_47db_m00awn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_30/bd_47db_m00wn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_31/bd_47db_m00bn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_33/bd_47db_m01s2a_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_34/bd_47db_m01arn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_35/bd_47db_m01rn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_36/bd_47db_m01awn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_37/bd_47db_m01wn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_38/bd_47db_m01bn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_40/bd_47db_m02s2a_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_41/bd_47db_m02arn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_42/bd_47db_m02rn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_43/bd_47db_m02awn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_44/bd_47db_m02wn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_1/ip/ip_45/bd_47db_m02bn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_0/ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/bd_c800_vsc_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c800_vsc_0 || ORIG_REF_NAME==bd_c800_vsc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/bd_c800_hsc_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c800_hsc_0 || ORIG_REF_NAME==bd_c800_hsc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_3/bd_c800_input_size_set_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_4/bd_c800_rst_axis_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c800_rst_axis_0 || ORIG_REF_NAME==bd_c800_rst_axis_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_4/bd_c800_rst_axis_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c800_rst_axis_0 || ORIG_REF_NAME==bd_c800_rst_axis_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_5/bd_c800_reset_sel_axis_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c800_reset_sel_axis_0 || ORIG_REF_NAME==bd_c800_reset_sel_axis_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_5/bd_c800_reset_sel_axis_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_5/bd_c800_reset_sel_axis_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c800_reset_sel_axis_0 || ORIG_REF_NAME==bd_c800_reset_sel_axis_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/ip/ip_6/bd_c800_axis_register_slice_0_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c800_axis_register_slice_0_0 || ORIG_REF_NAME==bd_c800_axis_register_slice_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_v_proc_ss_0_0/bd_0/bd_c800_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_1/bd_10d0_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_1/bd_10d0_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_2/bd_10d0_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_2/bd_10d0_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_3/bd_10d0_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_3/bd_10d0_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_4/bd_10d0_arinsw_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_5/bd_10d0_rinsw_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_6/bd_10d0_awinsw_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_7/bd_10d0_winsw_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_8/bd_10d0_binsw_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_9/bd_10d0_aroutsw_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_10/bd_10d0_routsw_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_11/bd_10d0_awoutsw_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_12/bd_10d0_woutsw_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_13/bd_10d0_boutsw_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_14/bd_10d0_arni_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_15/bd_10d0_rni_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_16/bd_10d0_awni_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_17/bd_10d0_wni_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_18/bd_10d0_bni_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_22/bd_10d0_s00a2s_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_23/bd_10d0_sarn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_24/bd_10d0_srn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_25/bd_10d0_sawn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_26/bd_10d0_swn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_27/bd_10d0_sbn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_28/bd_10d0_m00s2a_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_29/bd_10d0_m00arn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_30/bd_10d0_m00rn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_31/bd_10d0_m00awn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_32/bd_10d0_m00wn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_33/bd_10d0_m00bn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_35/bd_10d0_m01s2a_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_36/bd_10d0_m01arn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_37/bd_10d0_m01rn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_38/bd_10d0_m01awn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_39/bd_10d0_m01wn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/bd_0/ip/ip_40/bd_10d0_m01bn_0_ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/ip/Atelier2_bd_smartconnect_0_0/ooc.xdc

# XDC: c:/Users/freed/Desktop/Atelier2/Atelier2/Atelier2.gen/sources_1/bd/Atelier2_bd/Atelier2_bd_ooc.xdc
